package com.pass.model.domain;
// Generated 15 Jun, 2017 1:43:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NdbBinlogIndexId generated by hbm2java
 */
@Embeddable
public class NdbBinlogIndexId  implements java.io.Serializable {


     private long epoch;
     private int origServerId;
     private long origEpoch;

    public NdbBinlogIndexId() {
    }

    public NdbBinlogIndexId(long epoch, int origServerId, long origEpoch) {
       this.epoch = epoch;
       this.origServerId = origServerId;
       this.origEpoch = origEpoch;
    }
   


    @Column(name="epoch", nullable=false)
    public long getEpoch() {
        return this.epoch;
    }
    
    public void setEpoch(long epoch) {
        this.epoch = epoch;
    }


    @Column(name="orig_server_id", nullable=false)
    public int getOrigServerId() {
        return this.origServerId;
    }
    
    public void setOrigServerId(int origServerId) {
        this.origServerId = origServerId;
    }


    @Column(name="orig_epoch", nullable=false)
    public long getOrigEpoch() {
        return this.origEpoch;
    }
    
    public void setOrigEpoch(long origEpoch) {
        this.origEpoch = origEpoch;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NdbBinlogIndexId) ) return false;
		 NdbBinlogIndexId castOther = ( NdbBinlogIndexId ) other; 
         
		 return (this.getEpoch()==castOther.getEpoch())
 && (this.getOrigServerId()==castOther.getOrigServerId())
 && (this.getOrigEpoch()==castOther.getOrigEpoch());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getEpoch();
         result = 37 * result + this.getOrigServerId();
         result = 37 * result + (int) this.getOrigEpoch();
         return result;
   }   


}


